- name: Play to play with dictionary 
  hosts: apps
  vars:
   users:
    Prakhar:
      name: Prakhar Srivastava
      telephone: 667777777
    Mitesh:
      name: Mitesh Sharma
      telephone: 33922999
  tasks:

  - name: copy dict_facts.yml
    copy:
      src: dict_facts.yml
      dest: /home/devops/ansible_implementation
  - name: Print phone records
    debug:
      msg: "User {{ item.key }} is {{ item.value.name }} ({{ item.value.telephone }})"
    loop: "{{ lookup('dict', users) }}"
