---
- name: Play for web configuration
  hosts: support
  roles:
    - role: firewall_configuration
      rule_services: 
        - smtp
  tasks:
    - name: Import mail_configuration play
      import_role:
        name: mail_configuration

