---
- name: Copy custom library
  hosts: localhost
  tasks:
  - name: Copy hello-world.py  library
    copy:    
      src: hello-world.py
      dest: /home/devops/ansible_implementation/library/

  - name: Copy version_change.py  library
    copy:    
      src: version_change.py
      dest: /home/devops/ansible_implementation/library/

  - name: Test that my hello_world module works
    hello-world:
    register: result
  
  - debug: var=result

  - name: Test that my change_version module works
    version_change:
      version_name: "Before"
      version_no:  1.1.1
      unchanged_value: "This will pass through"
    register: result

  - debug: var=result
