- name: Create devops user
  user:
    name: "{{ user_name }}"
    password: "{{ user_password | password_hash('sha512') }}" 
    generate_ssh_key: True
    state: present

- name: get devops user's public key
  shell: cat /home/devops/.ssh/id_rsa.pub
  register: ssh_pubkey
  when: inventory_hostname == 'localhost'

- name: Copy ssh public key on all servers
  authorized_key: 
    user: "{{ user_name }}" 
    key: "{{ hostvars['localhost']['ssh_pubkey']['stdout'] }}"
  when: (copy_ssh_pubkey ) and ( inventory_hostname != 'localhost' )

- name: Sudoer user setup
  lineinfile:
    dest: /etc/sudoers 
    state: present 
    line: '{{ user_name }} ALL=(ALL) NOPASSWD: ALL'
  when: user_is_sudoer

- name: Create  log directory
  file:
    path: /home/devops/ansible_implementation
    state: directory
    owner: devops
    group: devops
    mode: 0775
