---
# handlers file for roles/db_configuration
- name: start_service 
  service:
    name: "{{ db_service }}"
    state: started
    enabled: true

- name: restart_service 
  service:
    name: "{{ db_service }}"
    state: restarted
    enabled: true

