---
# handlers file for roles/db_configuration
- name: start_service 
  service:
    name: "{{ db_service }}"
    state: started
    enabled: true

- name: restart_service 
  service:
    name: "{{ db_service }}"
    state: restarted
    enabled: true

- name: set_password
  mysql_user:
    name: root
    password: redhat
  ignore_errors: yes
  when: set_db_root_password
