---
- name: install samba
  yum: 
    name: samba
    state: "{{ install_state }}"

- name: debug install_state variable
  debug: 
    msg: "The state for the samba service is {{ install_state }}"

- name: start samba
  service:
    name: smb
    state: started
    enabled: yes

- name: deliver samba config
  template:
    src: samba.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644

