---
# defaults file for roles/db_configuration
db_package: mariadb-server
db_service: mariadb
db_users:
  - db_admin
  - db_user
configure_database_path: /etc/my.cnf
extra_packages:
  - mariadb-bench
  - mariadb-libs
  - mariadb-test

set_db_root_password: false
